Improve var. naming and comments here and there

diff --git a/tun2socks-manager b/tun2socks-manager
--- a/tun2socks-manager
+++ b/tun2socks-manager
@@ -3,18 +3,66 @@
 # TODO:
 # * Setup reverse DNS
 # * Default config that adds only SSH Server to route table
-#   * Possibly keeping local DNS, or enforcing remote DNS
+#   * Possibly keeping local DNS as reported by NM, or enforcing remote DNS
+#     Note: DNS can be collected with 
+#       $(nmcli dev show eth0 | perl -lne 'print for /^IP4.DNS.*: +([0-9.]+)/'))
 # * Remove dependency on NetworkManager?
 # * Issue: can't start virtualbox machine when tun2socks-manager is up
-
-# Collect DNS with
-#     FOODNS=($(nmcli dev show eth0 | perl -lne 'print for /^IP4.DNS.*: +([0-9.]+)/'))
 
 BASE=$(basename $0)
 CONFIG_MAIN_FILE=/etc/tun2socks-manager.conf
 CONFIG_GW_DIR=/etc/tun2socks-manager.d
 
+# Read configuration. First set default values, then source local config
+TUN2SOCKS_PROXY=127.0.0.1:1080
+TUN2SOCKS_UDPGW_REMOTE=127.0.0.1:7300
+TUN2SOCKS_LOGLEVEL=none
+TUN_IP=10.0.10.1
+TUN_IP_CIDR=24
+TUN_IP_GW=10.0.10.2
+TUN_IF=tun0
+TUN_CON=tun-$TUN_IF
+IPROUTE_TABLE=tun
+IPROUTE_TABLE_ID=100
+IPROUTE_TABLE_PRIO=1000
+
 . $CONFIG_MAIN_FILE
+
+# Functions to manipulate ip addresses
+ip_to_int()
+{
+    local IP=$1
+    echo $(( $(echo $IP | sed -r 's/^/(((/; s/\./)*256+/g') ))
+}
+
+cidr_to_int()
+{
+    local CIDR=$1
+    echo $(( (0xFFFFFFFF << (32-CIDR)) & 0xFFFFFFFF ))
+}
+
+int_to_ip()
+{
+    local INT=$1
+    local IP3=$(( (INT >> 24) & 0xFF ))
+    local IP2=$(( (INT >> 16) & 0xFF ))
+    local IP1=$(( (INT >> 8) & 0xFF ))
+    local IP0=$(( INT & 0xFF ))
+    echo "$IP3.$IP2.$IP1.$IP0"
+}
+
+cidr_to_mask()
+{
+    local CIDR=$1
+    int_to_ip $(cidr_to_int $CIDR)
+}
+
+ip_cidr_to_subnet()
+{
+    local IP_INT=$(ip_to_int $1)
+    local CIDR_INT=$(cidr_to_int $2)
+    int_to_ip $((IP_INT & CIDR_INT))
+}
 
 # 1: warning or non-permanent error
 # 3: permanent error (typically configuration error)
@@ -74,8 +122,8 @@ do_start()
     # Create new tun (temporary) connection if necessary
     if ! nmcli con show $TUN_CON &> /dev/null; then
         # TODO: Use dedicated user. Add 'owner $(id -u $TUN_USER)'.
-        syslog "Creating new connection $TUN_CON (ifname=$TUN_DEV, ip4=$IP_TUN/$IP_TUN_MASK)."
-        cmdlog nmcli con add ifname $TUN_DEV con-name $TUN_CON  save no type tun mode tun ip4 $IP_TUN/$IP_TUN_MASK gw4 0.0.0.0
+        syslog "Creating new connection $TUN_CON (ifname=$TUN_IF, ip4=$TUN_IP/$TUN_IP_CIDR)."
+        cmdlog nmcli con add ifname $TUN_IF con-name $TUN_CON  save no type tun mode tun ip4 $TUN_IP/$TUN_IP_CIDR gw4 0.0.0.0
     fi
 
     # Start connection if not active yet
@@ -87,9 +135,10 @@ do_start()
     # Start badvpn-tun2socks daemon if not running yet
     if ! pgrep badvpn-tun2sock &> /dev/null; then    # pgrep is limited to the 15 characters in /proc/pid/stat
         syslog "Starting badvpn-tun2socks daemon."
-        cmdlog su $TUN_USER -c "setsid badvpn-tun2socks --logger syslog --loglevel $TUN_LOGLEVEL \
-            --tundev $TUN_DEV --netif-ipaddr $IP_TUN_GW --netif-netmask $IP_TUN_GW_MASK \
-            --socks-server-addr $IP_SOCKS_PROXY --udpgw-remote-server-addr $IP_UDPGW"
+        local TUN_IP_GW_MASK=$(cidr_to_mask $TUN_IP_CIDR)
+        cmdlog su $TUN_USER -c "setsid badvpn-tun2socks --logger syslog --loglevel $TUN2SOCKS_LOGLEVEL \
+            --tundev $TUN_IF --netif-ipaddr $TUN_IP_GW --netif-netmask $TUN_IP_GW_MASK \
+            --socks-server-addr $TUN2SOCKS_PROXY --udpgw-remote-server-addr $TUN2SOCKS_UDPGW_REMOTE"
     fi
 }
 
@@ -102,7 +151,7 @@ do_stop()
     fi
 
     # Delete connection $TUN_CON
-    # NetworkManager will automatically delete attached device (TUN_DEV)
+    # NetworkManager will automatically delete attached device (TUN_IF)
     if nmcli con show $TUN_CON &> /dev/null; then
         syslog "Deleting connection $TUN_CON."
         cmdlog nmcli con delete $TUN_CON
@@ -111,18 +160,18 @@ do_stop()
 
 get_current_gw_and_itf()
 {
-    read REF_GW REF_IF < <( route -n | awk -v TUN_DEV=$TUN_DEV 'BEGIN {metric=10000; REF_IF="none"; REF_GW="0.0.0.0"} {if($1 == "0.0.0.0" && $5 < metric && $8 != TUN_DEV) { REF_IF=$8; REF_GW=$2; metric=$5} } END {print REF_GW " " REF_IF}')
+    read GW IF < <( route -n | awk -v TUN_IF=$TUN_IF 'BEGIN {metric=10000; IF="none"; GW="0.0.0.0"} {if($1 == "0.0.0.0" && $5 < metric && $8 != TUN_IF) { IF=$8; GW=$2; metric=$5} } END {print GW " " IF}')
 }
 
 do_up()
 {
     # Get current gateway and interface
     get_current_gw_and_itf
-    syslog "Current gateway is $REF_GW via interface $REF_IF."
-    [ "$REF_IF" != "none" ] || die 1 "Warning! No default interface or gateway found."
+    syslog "Current gateway is $GW via interface $IF."
+    [ "$IF" != "none" ] || die 1 "Warning! No default interface or gateway found."
 
     # Exit if we don't have a config file for the current gateway
-    TUN_CFG_FILE=$CONFIG_GW_DIR/$REF_GW
+    TUN_CFG_FILE=$CONFIG_GW_DIR/$GW
     if ! [ -e $TUN_CFG_FILE ]; then
         syslog "No config for current gateway. Create file '$TUN_CFG_FILE' to setup a tunnel."
         exit 0
@@ -133,9 +182,10 @@ do_up()
     # ... However our config may create another route in table tun that includes that subnet (e.g. 10.0.0.0/8).
     # ... If we don't duplicate kernet route in this table, this less specific route will take precedence, and
     # ... hence subnet 10.0.10.0/24 will become unreachable.
-    syslog "Duplicating $TUN_DEV link route from main table."
-    TUN_ROUTE_MAIN=$(ip route | sed -rn "/^$IP_TUN_SUBNET\/$IP_TUN_MASK/{s/linkdown +//; p}")
-    [ -n "$TUN_ROUTE_MAIN" ] || die 1 "Cannot find $TUN_DEV link route."
+    syslog "Duplicating $TUN_IF link route from main table."
+    local TUN_IP_SUBNET=$(ip_cidr_to_subnet $TUN_IP $TUN_IP_CIDR)
+    TUN_ROUTE_MAIN=$(ip route | sed -rn "/^$TUN_IP_SUBNET\/$TUN_IP_CIDR/{s/linkdown +//; p}")
+    [ -n "$TUN_ROUTE_MAIN" ] || die 1 "Cannot find $TUN_IF link route."
     cmdlog ip route add $TUN_ROUTE_MAIN table $IPROUTE_TABLE
 
     # Parsing configuration
@@ -146,8 +196,8 @@ do_up()
         case $CFG_TYPE in
             local )
                 [[ $A =~ ^[0-9.]+(/[0-9]+)?$ ]] || die 3 "Bad route '$A' in file '$TUN_CFG_FILE'."
-                syslog "- local route to net $A through interface $REF_IF."
-                cmdlog ip route add $A via $REF_GW table $IPROUTE_TABLE
+                syslog "- local route to net $A through interface $IF."
+                cmdlog ip route add $A via $GW table $IPROUTE_TABLE
                 ;;
             dns )
                 [[ $A =~ ^[0-9.]+$ ]] || die 3 "Bad DNS IP '$A' in file '$TUN_CFG_FILE'."
@@ -163,9 +213,9 @@ do_up()
         esac
     done < <(sed -r 's/#.*//' "$TUN_CFG_FILE")
 
-    syslog "Setting $IP_TUN_GW as default gateway."
+    syslog "Setting $TUN_IP_GW as default gateway."
     # Metric not needed. Will take precedence thanks to our new table and policy rule
-    cmdlog ip route add default via $IP_TUN_GW table $IPROUTE_TABLE
+    cmdlog ip route add default via $TUN_IP_GW table $IPROUTE_TABLE
 
     # Enable new routes and flush route cache
     syslog "Enabling route table '$IPROUTE_TABLE' and flushing cache."
@@ -216,10 +266,10 @@ COMMAND=$1
 shift
 
 # Only for update command
-IF=$1
-STATUS=$2
+CMD_IF=$1
+CMD_STATUS=$2
 
-syslog "Received command: $COMMAND${IF:+ $IF}${STATUS:+ $STATUS}."
+syslog "Received command: $COMMAND${CMD_IF:+ $CMD_IF}${CMD_STATUS:+ $CMD_STATUS}."
 
 if [ "$COMMAND" = install ]; then
     do_install
@@ -236,16 +286,16 @@ elif [ "$COMMAND" = up ]; then
 elif [ "$COMMAND" = down ]; then
     do_down
 elif [ "$COMMAND" = update ]; then
-    if [ -n "$IF" -a "$STATUS" == down ]; then
+    if [ -n "$CMD_IF" -a "$CMD_STATUS" == down ]; then
         # An interface went down. Exit if we don't route through it
-        if ! ip route show table $IPROUTE_TABLE | grep -q "dev $IF"; then
+        if ! ip route show table $IPROUTE_TABLE | grep -q "dev $CMD_IF"; then
             syslog "No change needed in current tunnel."
             exit 0
         fi
     fi
-    if [ -n "$IF" -a "$STATUS" == up ]; then
+    if [ -n "$CMD_IF" -a "$CMD_STATUS" == up ]; then
         # An interface went up. Exit if we route already through it
-        if ip route show table $IPROUTE_TABLE | grep -q "dev $IF"; then
+        if ip route show table $IPROUTE_TABLE | grep -q "dev $CMD_IF"; then
             syslog "No change needed in current tunnel."
             exit 0
         fi
